### 1. Créer l'utilisateur (Note le /signup)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "adam@hotmail.com",
    "password": "un-vrai-mot-de-passe",
    "name" : "adam"
}

### 2. Récupérer tout les utilisateurs

GET http://localhost:3000/auth
Accept: application/json

### 3. Récupérer l'utilisateur par nom
GET http://localhost:3000/auth/email/sara@hotmail.com
Accept: application/json

### 4. Récupérer l'utilisateur par id
GET http://localhost:3000/auth/1
Accept: application/json