### Create user test

POST http://localhost:3000/users
Content-Type: application/json

{
    "email" : "sara@hotmail.com",
    "password": "mdp",
    "name" : "sara"
}

### Get user by name (Path Param)
GET http://localhost:3000/users/sara
Accept: application/json