############################################################
# 1. AUTHENTIFICATION & UTILISATEURS
############################################################

### Créer un utilisateur
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "yassine@gmail.com",
    "password": "123",
    "name": "Yassine",
    "profile": 1,
    "dateNaissance": "2015-01-01"
}

### Créer un administrateur
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@hotmail.com",
    "password": "123",
    "name": "The Boss",
    "profile": 2,
    "dateNaissance": "2016-02-02"
}

### Se connecter
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "yassine@gmail.com",
    "password": "123"
}

### Se connecter admin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin@hotmail.com",
    "password": "123"
}

### WhoamI
GET http://localhost:3000/auth/whoAmI

### Se déconnecter
POST http://localhost:3000/auth/signout

### Liste utilisateurs
GET http://localhost:3000/auth

### Trouver par email
GET http://localhost:3000/auth/email/yassine@gmail.com

### Trouver par ID
GET http://localhost:3000/auth/1

### Modifier utilisateur
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "name": "Yassine Modifié"
}


############################################################
# 2. GESTION DES CELLULES
############################################################

### Créer une cellule
POST http://localhost:3000/cellules
Content-Type: application/json

{
    "nom": "A1"
}

### Liste des cellules
GET http://localhost:3000/cellules

### Voir une cellule
GET http://localhost:3000/cellules/1

### Modifier une cellule
PATCH http://localhost:3000/cellules/1
Content-Type: application/json

{
    "nom": "A1-Modifiée"
}


############################################################
# 3. GESTION DES PRISONNIERS
############################################################

### Ajouter un prisonnier
POST http://localhost:3000/prisonniers
Content-Type: application/json

{
    "nom": "Adam",
    "prenom": "Roy",
    "dateNaissance": "1959-08-22",
    "accusation": "Racketeering, Extortion",
    "dureePeine": 20,
    "dateArrivee": "2026-04-01",
    "dateSortiePrevue": "2046-04-01",
    "photoProfil": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1Oj_OnZz5cqZ_aibLOHTP_tUTIYR7E5r9vA&s",
    "celluleNom": "A1"
}

### Liste des prisonniers
GET http://localhost:3000/prisonniers

### Voir un prisonnier
GET http://localhost:3000/prisonniers/1

### Modifier un prisonnier
PATCH http://localhost:3000/prisonniers/6
Content-Type: application/json

{
    "photoProfil": "https://imgur.com/a/GYSiURn"
}


############################################################
# 4. GESTION DES INCIDENTS
############################################################

### Créer un incident
POST http://localhost:3000/incidents
Content-Type: application/json

{
    "type": "Bagarre",
    "description": "Une bagarre a éclaté dans la cour entre deux détenus",
    "dateHeure": "2026-04-15T10:30:00",
    "rapportePar": "Garde Dupont",
    "prisonniersIds": [1]
}

### Liste des incidents
GET http://localhost:3000/incidents

### Voir un incident
GET http://localhost:3000/incidents/1


############################################################
# 5. GESTION DES VISITES
############################################################

### Demander une visite
POST http://localhost:3000/visites
Content-Type: application/json

{
    "prisonnierId": 1,
    "nomMembreFamille": "Adam Roy",
    "lienFamilial": "Frère"
}

### Liste des visites
GET http://localhost:3000/visites

### Voir les demandes en attente
GET http://localhost:3000/visites/en-attente

### Voir dossier prisonnier
GET http://localhost:3000/visites/dossier/1

### Répondre à une demande
PATCH http://localhost:3000/visites/1/repondre
Content-Type: application/json

{
    "decision": "approuvee",
    "dateVisite": "2026-04-20T14:00:00"
}
